# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.sheild.root] run return 0
execute on passengers if entity @s[tag=aj.sheild.data] unless data entity @s {data:{rigHash: '0e2cab14814ffca557e2e76470dd97b7cc4bc3a759e649b08038a156fff1fc65'}} on vehicle run function animated_java:sheild/root/zzz/check_rig_hash
scoreboard players set @s aj.is_rig_loaded 1