# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=minecraft:item_display,tag=aj.sheild.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'sheild', 'function_path': 'animated_java:sheild/animations/deploy/stop'}
tag @s remove aj.sheild.animation.deploy.playing
scoreboard players set @s aj.deploy.frame 0
tag @s add aj.transforms_only
execute at @s run function animated_java:sheild/animations/deploy/zzz/set_frame {frame: 0}
tag @s remove aj.transforms_only